import 'server-only'
import { createServiceClient } from '@/lib/supabase-server'
import { sendFounderAlertEmail } from '@/lib/email/founder-mailer'
import { policyFor } from './errors'
import type { AICallContext, AIErrorCategory, AIProviderId, AIRouting, AITask } from './types'

/**
 * Founder-visible alerting for AI provider degradation.
 *
 * WHY THIS EXISTS
 * On 2026-09-02 the Anthropic account ran out of credit. Claude served zero
 * calls between 02:00 and 21:00 UTC — nineteen hours — and the gateway did
 * exactly what it was built to do: it failed over to OpenAI and kept Caye
 * running. Customer-facing front-desk replies were generated by `gpt-5`
 * instead of the Sonnet the voice/guards/evals are tuned on, three requests
 * failed outright when OpenRouter also returned 402, and *nothing told
 * anyone*. The whole incident is legible only because `llm_call_log.attempts`
 * recorded the provider trail after the fact.
 *
 * Silent failover is the correct runtime behaviour and is not changed here.
 * What was missing is that nobody learns the primary vendor is dead.
 *
 * WHAT THIS IS NOT
 * Not a second telemetry system. Every call still writes exactly one
 * `llm_call_log` row via lib/ai/telemetry.ts, and that stays the ledger.
 * This module reads decisions the gateway has *already* made and pages a
 * human when one of them means "an account is broken", nothing more. It
 * owns no state beyond the dedup rows it inserts.
 *
 * SEVERITY COMES FROM FAILURE_POLICY, NOT FROM A NEW TAXONOMY
 * lib/ai/errors.ts already separates account facts from blips: an account
 * fact opens the circuit on the FIRST failure (`failureThreshold === 1`),
 * because an exhausted balance or a bad key does not fix itself in 60s. A
 * transient fault needs three. `isAccountFatal` below is that existing
 * policy read back, so a change to FAILURE_POLICY moves alerting with it
 * and the two can never disagree.
 *
 * DELIVERY: EMAIL, DELIBERATELY
 * lib/whatsapp/founder-alert.ts learned this the hard way (see
 * briefs/whatsapp-delivery-reliability.md): an alarm must not travel over
 * the thing it is reporting broken. Resend depends on no AI provider, so it
 * is the correct channel for an AI outage. WhatsApp is deliberately NOT
 * wired in here — it would make the AI gateway depend on the WhatsApp
 * outbound stack for no reliability gain, since Resend is already
 * independent of the failure.
 *
 * FAIL-OPEN, ALWAYS
 * Same contract as `logAiCall`: alerting must never fail, delay, or change
 * a model response. Every entry point is fire-and-forget and swallows its
 * own errors. A broken alerter is a lost alert, never a lost reply.
 */

/** Existing `caye_founder_alert_log` (20260726c) — insert-or-skip on a unique key. No migration needed. */
const ALERT_LOG_TABLE = 'caye_founder_alert_log'

const HOUR_MS = 60 * 60 * 1000
/**
 * Total chain failure means Caye answered nobody. Deduped far tighter than
 * the hourly incident classes so a real outage is noticed in minutes, and
 * because — unlike a fallback — it should be rare enough not to spam.
 */
const CHAIN_EXHAUSTED_DEDUP_MS = 15 * 60 * 1000

/**
 * Tasks where a silent vendor change is a product fact, not just an infra
 * one: a person is waiting on the other end and the output is shaped by
 * prompts and guards tuned per-model. Background extraction/classification
 * failing over is genuinely routine and stays in the ledger without paging.
 */
const USER_FACING_TASKS: ReadonlySet<AITask> = new Set<AITask>([
  'customer_response',
  'operator_response',
  'agent_planning',
  'onboarding',
])

/**
 * An account-level failure, derived from the existing policy table rather
 * than a second hand-maintained list: these are the categories that open
 * the circuit on a single occurrence (billing_exhausted, authentication,
 * quota). Everything else needs repetition before it counts as anything.
 */
export function isAccountFatal(category: AIErrorCategory): boolean {
  const policy = policyFor(category)
  return policy.opensCircuit && policy.failureThreshold === 1
}

export function isUserFacingTask(task: AITask): boolean {
  return USER_FACING_TASKS.has(task)
}

/**
 * Provider error text is echoed into an email, so it gets scrubbed first.
 * Providers do not normally quote credentials back, but "normally" is not a
 * guarantee worth betting a leaked key on — a 400 body can carry request
 * headers, and this text is already truncated from an untrusted source.
 *
 * Ordered deliberately: labelled key/value pairs first (so the label
 * survives and reads as a redaction), then recognisable key shapes, then a
 * conservative catch-all for long opaque strings. The 40-char floor on the
 * catch-all is above every id Caye legitimately surfaces (Anthropic request
 * ids are ~27, model ids far shorter), so real diagnostic detail survives.
 */
export function redactSecrets(text: string): string {
  return text
    // The optional auth scheme is consumed with the value: without it,
    // `Authorization: Bearer <token>` redacted only the word "Bearer" and
    // left the credential in place. Caught by its own test.
    .replace(
      /("?(?:api[_-]?key|authorization|x-api-key|access[_-]?token|refresh[_-]?token|token|secret|password)"?\s*[:=]\s*)("?)(?:(?:Bearer|Basic|Token)\s+)?[^"\s,;}]+("?)/gi,
      '$1$2[redacted]$3'
    )
    .replace(/\b(?:sk|pk|rk)-[A-Za-z0-9_-]{8,}/g, '[redacted]')
    .replace(/\bBearer\s+[A-Za-z0-9._-]{8,}/gi, 'Bearer [redacted]')
    .replace(/\b[A-Za-z0-9_-]{40,}\b/g, '[redacted]')
}

/** Bounded even after redaction — an alert is a signal, not a log tail. */
function safeDetail(detail: string | null | undefined, max = 240): string {
  if (!detail) return ''
  const clean = redactSecrets(detail).trim()
  return clean.length > max ? `${clean.slice(0, max)}…` : clean
}

export type DegradationKind =
  | 'chain_exhausted'
  | 'account_fatal'
  | 'user_facing_fallback'
  | 'provider_recovered'

interface AlertPlan {
  kind: DegradationKind
  /** Unique per incident-window; collides on repeats so the insert skips. */
  alertKey: string
  subject: string
  body: string
}

/**
 * One incident, one alert per window. The key never includes a workspace for
 * account-level classes: an exhausted vendor account breaks every workspace
 * at once, and one alert per workspace is how the WhatsApp path once turned
 * a single outage into a burst of near-identical pages.
 */
function bucket(ms: number): number {
  return Math.floor(Date.now() / ms)
}

function planFor(
  event: DegradationEvent
): AlertPlan {
  switch (event.kind) {
    case 'chain_exhausted': {
      const trail = event.routing.attempts
        .map((a) => `${a.provider}/${a.model}: ${a.outcome}`)
        .join(' → ')
      return {
        kind: event.kind,
        alertKey: `ai-chain-exhausted-${bucket(CHAIN_EXHAUSTED_DEDUP_MS)}`,
        subject: 'Caye URGENT: every AI provider failed — requests are not being served',
        body:
          `Every provider in the route failed for task "${event.routing.task}". ` +
          `Caye could not answer this request at all.\n\n` +
          `Source: ${event.ctx.source}\n` +
          `Attempts: ${trail}\n` +
          (event.detail ? `Last error: ${safeDetail(event.detail)}\n` : '') +
          `\nThis is not a failover — nothing served the request.`,
      }
    }
    case 'account_fatal':
      return {
        kind: event.kind,
        alertKey: `ai-account-fatal-${event.provider}-${event.category}-${bucket(HOUR_MS)}`,
        subject: `Caye: ${event.provider} is account-down (${event.category})`,
        body:
          `${event.provider} returned "${event.category}" — an account-level failure, not a transient one. ` +
          `Every workspace using ${event.provider} is affected until it is resolved.\n\n` +
          `Task: ${event.task}\n` +
          `Source: ${event.ctx.source}\n` +
          (event.detail ? `Provider said: ${safeDetail(event.detail)}\n` : '') +
          `\nCaye is failing over to the next provider in the route where one is available. ` +
          `Requests are still being served, but not by ${event.provider}.`,
      }
    case 'user_facing_fallback':
      return {
        kind: event.kind,
        alertKey: `ai-user-fallback-${event.routing.task}-${event.from}-${bucket(HOUR_MS)}`,
        subject: `Caye: user-facing traffic moved off ${event.from} (${event.routing.task})`,
        body:
          `A user-facing "${event.routing.task}" request was served by ${event.routing.provider} ` +
          `(${event.routing.model}) instead of ${event.from}, because ${event.from} returned ` +
          `"${event.category}".\n\n` +
          `Source: ${event.ctx.source}\n` +
          `Workspace: ${event.ctx.workspaceId ?? 'n/a'}\n` +
          `\nThe request succeeded. Worth knowing because prompts, voice and output guards ` +
          `are tuned on the primary model — a different vendor answering a customer is a ` +
          `product change, not just an infrastructure one.`,
      }
    case 'provider_recovered':
      return {
        kind: event.kind,
        alertKey: `ai-recovered-${event.provider}-${bucket(HOUR_MS)}`,
        subject: `Caye: ${event.provider} is serving again`,
        body:
          `${event.provider} completed a request successfully after previously being in cooldown` +
          (event.previousReason ? ` (${event.previousReason})` : '') +
          `.\n\nTask: ${event.routing.task}\nModel: ${event.routing.model}\n` +
          `\nRouting has returned to normal for this provider.`,
      }
  }
}

export type DegradationEvent =
  | { kind: 'chain_exhausted'; ctx: AICallContext; routing: AIRouting; detail?: string | null }
  | {
      kind: 'account_fatal'
      ctx: AICallContext
      provider: AIProviderId
      category: AIErrorCategory
      task: AITask
      detail?: string | null
    }
  | {
      kind: 'user_facing_fallback'
      ctx: AICallContext
      routing: AIRouting
      from: AIProviderId
      category: AIErrorCategory
    }
  | {
      kind: 'provider_recovered'
      ctx: AICallContext
      routing: AIRouting
      provider: AIProviderId
      previousReason?: AIErrorCategory | null
    }

/**
 * Fire-and-forget. Mirrors `logAiCall`: never throws, never awaited by a
 * request path. Exported for tests that want to assert the decision without
 * racing the void.
 */
export function alertProviderDegradation(event: DegradationEvent): void {
  void deliverDegradationAlert(event).catch((error) => {
    console.error(
      '[ai/degradation-alert] alert failed:',
      error instanceof Error ? error.message : String(error)
    )
  })
}

export async function deliverDegradationAlert(event: DegradationEvent): Promise<'sent' | 'deduped' | 'skipped'> {
  const plan = planFor(event)

  const supabase = createServiceClient()

  // Claim the incident window before doing anything observable. A repeat key
  // fails on the primary key (23505) and we stop — the same insert-or-skip
  // guard lib/whatsapp/founder-alert.ts uses, against the same table.
  const { error: dedupError } = await supabase.from(ALERT_LOG_TABLE).insert({ alert_key: plan.alertKey })
  if (dedupError) {
    if (dedupError.code === '23505') return 'deduped'
    console.error('[ai/degradation-alert] dedup claim failed:', dedupError.message)
    return 'skipped'
  }

  const { data: setting } = await supabase
    .from('platform_settings')
    .select('value')
    .eq('key', 'founder_email')
    .maybeSingle()
  const founderEmail = (setting?.value as string | undefined) ?? undefined

  if (!founderEmail) {
    // Losing the alert is bad; losing it silently is worse. The console line
    // is the last resort and still carries the redacted detail.
    console.error(`[ai/degradation-alert] ${plan.kind} but no founder_email configured — ${plan.subject}`)
    return 'skipped'
  }

  const result = await sendFounderAlertEmail({
    to: founderEmail,
    subject: plan.subject,
    body: plan.body,
  })
  if (!result.ok) {
    console.error(`[ai/degradation-alert] ${plan.kind} email failed:`, result.error)
    return 'skipped'
  }
  return 'sent'
}

/**
 * Decide whether a completed route warrants a fallback alert.
 *
 * Deliberately narrow: only an *account-level* cause pages. A rate limit or
 * a 5xx that failed over is normal operation, is already in `llm_call_log`,
 * and paging on it would train the founder to ignore this mailbox — which
 * is the failure mode that made the 19-hour outage invisible in the first
 * place. Returns the triggering attempt so the caller can name the cause.
 */
export function accountFatalFallbackCause(
  routing: AIRouting
): { from: AIProviderId; category: AIErrorCategory } | null {
  if (!routing.fellBack) return null
  if (!isUserFacingTask(routing.task)) return null
  for (const attempt of routing.attempts) {
    const outcome = attempt.outcome
    if (outcome === 'success') break
    if (outcome.startsWith('skipped_')) continue
    const category = outcome as AIErrorCategory
    if (isAccountFatal(category)) return { from: attempt.provider, category }
  }
  return null
}
