import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { readFileSync } from 'node:fs'; import { join } from 'node:path'; import { PGlite } from '@electric-sql/pglite'

describe('domain integration corrective migration',()=>{
  let db:PGlite
  beforeAll(async()=>{ db=new PGlite(); await db.exec(`
    create table public.customers(id uuid primary key default gen_random_uuid());
    create table public.business_artifacts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.customers(id) on delete cascade);
    create table public.workspace_events(id bigint generated always as identity primary key,workspace_id uuid not null,occurred_at timestamptz not null,type text not null,actor_kind text not null,is_failure boolean not null default false,conversation_id uuid,subject_table text,subject_id text,payload jsonb not null default '{}'::jsonb,origin text);
    do $$ begin if not exists(select from pg_roles where rolname='anon')then create role anon;end if;if not exists(select from pg_roles where rolname='authenticated')then create role authenticated;end if;if not exists(select from pg_roles where rolname='service_role')then create role service_role;end if;end $$;
  `); const d=join(__dirname,'..','..','supabase','migrations'); for(const f of ['20260901190000_business_entity_kernel.sql','20260901_domain_event_projection_bridge.sql','20260902043000_domain_integration_review_fixes.sql']) await db.exec(readFileSync(join(d,f),'utf8')) })
  afterAll(async()=>db.close())
  async function ws(){return (await db.query<{id:string}>('insert into customers default values returning id')).rows[0].id}
  it('rejects cross-workspace artifact provenance and accepts same-workspace provenance',async()=>{const a=await ws(),b=await ws();const ea=(await db.query<{id:string}>(`insert into business_entities(workspace_id,domain,entity_type,authority,native_key) values($1,'x','a','caye_authoritative','a'),($1,'x','b','caye_authoritative','b') returning id`,[a])).rows;const artA=(await db.query<{id:string}>('insert into business_artifacts(workspace_id) values($1) returning id',[a])).rows[0].id;const artB=(await db.query<{id:string}>('insert into business_artifacts(workspace_id) values($1) returning id',[b])).rows[0].id;await expect(db.query(`insert into business_entity_relations(workspace_id,subject_entity_id,object_entity_id,relation_type,asserted_by,source_artifact_id) values($1,$2,$3,'rel','operator',$4)`,[a,ea[0].id,ea[1].id,artB])).rejects.toThrow();await expect(db.query(`insert into business_entity_relations(workspace_id,subject_entity_id,object_entity_id,relation_type,asserted_by,source_artifact_id) values($1,$2,$3,'rel','operator',$4)`,[a,ea[0].id,ea[1].id,artA])).resolves.toBeTruthy()})
  it('rejects nonexistent workspaces and cross-workspace observation entities while allowing null identity',async()=>{const a=await ws(),b=await ws();const entity=(await db.query<{id:string}>(`insert into business_entities(workspace_id,domain,entity_type,authority,native_key) values($1,'x','a','caye_authoritative','a') returning id`,[b])).rows[0].id;const missing='00000000-0000-0000-0000-000000000099';await expect(db.query(`insert into domain_sync_cursors(workspace_id,source_system,source_company_id,stream) values($1,'bedrock','c','po')`,[missing])).rejects.toThrow();await expect(db.query(`insert into domain_entity_observation_state(workspace_id,source_system,source_company_id,source_entity_type,source_entity_id,caye_entity_id,last_occurred_at,last_observed_at,last_idempotency_key) values($1,'bedrock','c','purchase_order','1',$2,now(),now(),'k')`,[a,entity])).rejects.toThrow();await expect(db.query(`insert into domain_entity_observation_state(workspace_id,source_system,source_company_id,source_entity_type,source_entity_id,caye_entity_id,last_occurred_at,last_observed_at,last_idempotency_key) values($1,'bedrock','c','purchase_order','2',null,now(),now(),'k2')`,[a])).resolves.toBeTruthy()})
  it('cascades bridge state when a workspace is deleted',async()=>{const a=await ws();await db.query(`insert into domain_sync_cursors(workspace_id,source_system,source_company_id,stream) values($1,'bedrock','c','po')`,[a]);await db.query('delete from customers where id=$1',[a]);expect((await db.query('select * from domain_sync_cursors where workspace_id=$1',[a])).rows).toHaveLength(0)})
})
