import 'server-only'
import { createServiceClient } from '@/lib/supabase-server'
import type { Tool } from '../types'

interface OutreachLeadInput {
  email: string
  business_name?: string
  contact_name?: string
  /**
   * Subject line for this first-touch email. Required — email sends have
   * no thread to inherit a subject from at this stage, unlike a reply.
   */
  subject: string
  /**
   * The cold-opener email body Caye writes in this same turn, following
   * outreach-script.md's opener template in the founder's voice — never
   * generated by a second model call, since the agent handling this tool
   * call is already an LLM turn that can write it directly.
   */
  draft: string
}

interface CreateOutreachLeadsInput {
  leads: OutreachLeadInput[]
}

/**
 * Bulk lead intake for TropiTech's own cold-outreach workspace (issue #66
 * follow-on) — the operator pastes a list of researched leads (from
 * Claude.ai or wherever) into the back-office chat, Caye drafts a
 * cold-opener per lead, and this tool creates a lead row + a held
 * conversation thread per address with that draft sitting in
 * metadata.proposed_reply — same hold_kind pattern as the automated
 * follow-up nudges (lib/outreach-nudge.ts), just hold_kind='outreach_
 * first_touch' so CommandConversations' compose box auto-fills it too.
 *
 * Deliberately NEVER sends anything — this is create-and-hold only.
 * Fully autonomous first-touch to brand-new cold contacts is permanently
 * off the table regardless of draft quality (decisions-log 2026-07-21,
 * staged autonomy roadmap, step 4) — the founder reviews and sends each
 * one from the dashboard compose box. Sending is what flips outreach_
 * leads.status from 'draft' to 'sent' and sets first_touch_sent_at (see
 * /api/messages/send), which is what makes the follow-up-nudge cron
 * correctly pick these up 2 days later if they go quiet.
 */
export const createOutreachLeads: Tool<CreateOutreachLeadsInput> = {
  name: 'create_outreach_leads',
  description:
    "Create draft-and-hold cold-outreach threads from a pasted list of leads (emails, optionally " +
    "with business/contact names or context the operator shared). For EACH lead, write a short, plain " +
    "subject line (e.g. 'Quick question about your booking messages' — no clickbait, no emoji) and a " +
    "cold-opener email body following outreach-script.md's opener template. Two structural rules that " +
    "are NOT optional and NOT covered by your voice profile (grilled 2026-07-23, a real batch violated " +
    "both): " +
    "(1) ALWAYS open by saying who you are — 'I'm Lamar with TropiTech' or 'I run TropiTech, a Bahamian " +
    "tech company' — before any observation about their business. A draft that jumps straight into " +
    "'I was researching X and came across your business' with no self-intro is wrong, every time. " +
    "(2) When writing multiple leads in the same batch, actively VARY the opening structure/verbs " +
    "between them — do not reuse the same 'I was looking into/researching X and came across Y' shape " +
    "for every lead just with the business details swapped in. That sameness is exactly what makes " +
    "outreach read as bulk-generated instead of individually written, even when each one is factually " +
    "personalized. " +
    "STRUCTURE (2026-07-29 — direct-pitch, live A/B test, replaces the older 'ask a pain-point question " +
    "and defer the pitch' opener): state what Caye is and the ask plainly in the first email, don't make " +
    "them guess where you're going. In order: (a) self-intro (rule 1 above), (b) one sentence naming " +
    "their specific situation, (c) one sentence stating what Caye is and does BY NAME — she answers " +
    "WhatsApp messages and books customers even while they're busy, (d) the proof point: one tour " +
    "operator in the Bahamas already using her (never overclaim more than the one real paying customer), " +
    "(e) one direct ask — 'Want to try it free?' or the self-serve meetcaye.com link. Never both, and " +
    "never a rhetorical question standing in for a real ask. " +
    "LENGTH (not optional, same standard as any real first-contact email): 3-4 sentences max, one clear " +
    "ask. A cold prospect gives this about 5 seconds — no founder-story preamble ('looking for a few " +
    "businesses to try it and help shape the product'), no explaining the product at length before the " +
    "ask. One CTA only: the direct ask in (e) above or the self-serve demo link — never stack both " +
    "in the same email. If you can't say it in 3-4 sentences, cut, don't add a paragraph break. Pass the " +
    "subject as `subject` and the body as `draft`. This tool ONLY creates the lead + a held thread with " +
    "your draft sitting in the dashboard's Review tab for the operator to read, edit, and send " +
    "themselves — it never sends anything and never will, regardless of how many leads are in the list " +
    "or how the operator phrases the request. Only available on the internal_sales (cold-outreach) " +
    "workspace — will error on any other workspace.",
  risk: 'low',
  roles: ['owner', 'founder'],
  modes: ['back-office'],
  inputSchema: {
    type: 'object',
    properties: {
      leads: {
        type: 'array',
        description: 'One entry per lead from the pasted list.',
        items: {
          type: 'object',
          properties: {
            email: { type: 'string', description: "The lead's email address." },
            business_name: { type: 'string', description: 'Business name, if known.' },
            contact_name: { type: 'string', description: 'Contact person\'s name, if known.' },
            subject: {
              type: 'string',
              description:
                'Short, plain subject line for this first-touch email. Required — there is no ' +
                'existing thread to inherit a subject from at this stage.',
            },
            draft: {
              type: 'string',
              description:
                "The cold-opener email body you wrote for this lead, signed as the founder, " +
                'never as Caye or an AI. Body only, no subject line, no em dashes.',
            },
          },
          required: ['email', 'subject', 'draft'],
        },
      },
    },
    required: ['leads'],
  },

  async execute(args, ctx) {
    if (!args.leads || args.leads.length === 0) {
      return { ok: false, error: 'No leads provided' }
    }

    const supabase = createServiceClient()

    const { data: workspace } = await supabase
      .from('customers')
      .select('workspace_kind')
      .eq('id', ctx.workspaceId)
      .maybeSingle()
    if (workspace?.workspace_kind !== 'internal_sales') {
      return {
        ok: false,
        error: 'This tool only works on the cold-outreach (internal_sales) workspace.',
      }
    }

    const { data: account } = await supabase
      .from('connected_accounts')
      .select('id')
      .eq('user_id', ctx.workspaceId)
      .eq('channel_type', 'email')
      .eq('is_active', true)
      .maybeSingle()
    if (!account) {
      return { ok: false, error: 'No active email connection on this workspace yet.' }
    }

    const created: string[] = []
    const skipped: string[] = []
    const errors: string[] = []

    for (const lead of args.leads) {
      const email = lead.email.trim().toLowerCase()
      const draft = lead.draft.trim()
      const subject = lead.subject?.trim()
      if (!email || !draft || !subject) {
        errors.push(`${lead.email || '(missing email)'}: missing email, subject, or draft`)
        continue
      }

      const { data: insertedLead, error: leadErr } = await supabase
        .from('outreach_leads')
        .insert({
          workspace_id: ctx.workspaceId,
          lead_email: email,
          business_name: lead.business_name ?? null,
          contact_name: lead.contact_name ?? null,
          status: 'draft',
        })
        .select('id')
        .single()

      if (leadErr) {
        // Unique violation (workspace_id, lead_email) — already a lead on file.
        if (leadErr.code === '23505') {
          skipped.push(email)
        } else {
          errors.push(`${email}: ${leadErr.message}`)
        }
        continue
      }

      const { error: convErr } = await supabase.from('unified_conversations').insert({
        connected_account_id: account.id,
        channel_type: 'email',
        channel_conversation_id: `outreach_${insertedLead.id}`,
        // Not ?? — Caye sometimes sends contact_name/business_name as "" rather
        // than omitting the field, and "" ?? x still returns "" (nullish
        // coalescing only falls through on null/undefined). That was leaving
        // customer_name blank — displaying as "Unknown" — for every lead
        // where no contact name was known, even though business_name was
        // correctly saved right next to it.
        customer_name: lead.contact_name?.trim() || lead.business_name?.trim() || email,
        customer_id: email,
        status: 'open',
        is_archived: false,
        human_agent_enabled: true,
        human_agent_reason: 'First-touch draft ready for review',
        metadata: {
          source: 'outreach_leads',
          lead_id: insertedLead.id,
          hold_kind: 'outreach_first_touch',
          subject,
          proposed_reply: draft,
        },
      })

      if (convErr) {
        errors.push(`${email}: thread creation failed (${convErr.message})`)
        continue
      }

      created.push(email)
    }

    return {
      ok: true,
      data: {
        created_count: created.length,
        created,
        skipped_existing: skipped,
        errors,
      },
    }
  },
}
