import 'server-only'
import { createServiceClient } from '@/lib/supabase-server'
import { hasSalesCapability } from '@/lib/sales/capability'
import type { Tool } from '../types'

interface OutreachLeadInput {
  email: string
  business_name?: string
  contact_name?: string
  /**
   * Subject line for this first-touch email. Required — email sends have
   * no thread to inherit a subject from at this stage, unlike a reply.
   */
  subject: string
  /**
   * The cold-opener email body Caye writes in this same turn, following
   * outreach-script.md's opener template in the founder's voice — never
   * generated by a second model call, since the agent handling this tool
   * call is already an LLM turn that can write it directly.
   */
  draft: string
}

interface CreateOutreachLeadsInput {
  leads: OutreachLeadInput[]
}

/**
 * Bulk lead intake for TropiTech's own cold-outreach workspace (issue #66
 * follow-on) — the operator pastes a list of researched leads (from
 * Claude.ai or wherever) into the back-office chat, Caye drafts a
 * cold-opener per lead, and this tool creates a lead row + a held
 * conversation thread per address with that draft sitting in
 * metadata.proposed_reply — same hold_kind pattern as the automated
 * follow-up nudges (lib/outreach-nudge.ts), just hold_kind='outreach_
 * first_touch' so CommandConversations' compose box auto-fills it too.
 *
 * Deliberately NEVER sends anything — this is create-and-hold only. This
 * is the manual, operator-fed path for a lead someone researched by hand;
 * app/api/caye/outreach-sourcing-scan + outreach-autosend-scan are the
 * autonomous path (decisions-log 2026-08-12, which reversed the prior
 * "step 4 permanently off" rule for that autonomous path — this tool's
 * own always-hold behavior is unrelated and unchanged by that reversal,
 * it's just a different, still-manual entry point into the same
 * outreach_leads table). The founder reviews and sends each one from the
 * dashboard compose box. Sending is what flips outreach_leads.status from
 * 'draft' to 'sent' and sets first_touch_sent_at (see /api/messages/send),
 * which is what makes the follow-up cadence correctly pick these up if
 * they go quiet.
 */
export const createOutreachLeads: Tool<CreateOutreachLeadsInput> = {
  name: 'create_outreach_leads',
  description:
    "Create draft-and-hold cold-outreach threads from a pasted list of leads (emails, optionally " +
    "with business/contact names or context the operator shared). For EACH lead, write a short, plain " +
    "subject line (e.g. 'Quick question about your booking messages' — no clickbait, no emoji) and a " +
    "cold-opener email body following outreach-script.md's opener template. " +
    "STRUCTURE (2026-07-29, converged over several real batches — problem-first, not intro-first, " +
    "replaces every earlier version of this rule): exactly 4 beats, in order: " +
    "(1) HOOK — one sentence, personalized (see PERSONALIZATION below): name the business, then state a " +
    "confident, un-hedged truth about their situation. Never guess or soften with 'probably', 'likely', " +
    "'I'd guess' — 'While you're busy running [Business], WhatsApp messages keep coming in' is right; " +
    "'Customers messaging [Business] probably wait a while' is wrong, it invites 'actually, maybe not'. " +
    "(2) SELF-ID + WHAT CAYE DOES — geography-conditional (2026-07-28, ICP widened to global + US, see " +
    "decisions-log): for a CARIBBEAN lead, 'I'm Lamar, founder of TropiTech, a Bahamian tech company. I " +
    "built Caye.' — the Bahamian mention is a real trust lever there (confirmed: Davia Smith and Michael " +
    "Frank both engaged partly on shared-island credibility), keep it. For a NON-Caribbean lead (US, " +
    "Mexico, anywhere else), drop the geography claim entirely: 'I'm Lamar, founder of TropiTech. I built " +
    "Caye.' Selling on what the product does, not where it's from, same reason horizontal SaaS tools don't " +
    "lead with their HQ city. Never say 'AI', 'automation', or 'LLM' anywhere in this email — describe the job, not the " +
    "category, and let them ask how it works once they've replied. Say what her job is, in JOB-DESCRIPTION " +
    "language, never a bare label: never 'an assistant', 'a chatbot', 'an AI employee/teammate', 'a " +
    "receptionist' — those are categories, not jobs. Keep it short and visual: 'She lives in WhatsApp, " +
    "making sure every customer gets a reply before they give up and move on.' Living inside WhatsApp " +
    "itself is the single most distinctive true thing about her — it pre-answers 'do I need another app?' " +
    "before they ask, so it belongs in this sentence, not buried later. Never promise a specific business " +
    "outcome you can't verify (not 'turns every message into a sale' — 'gets a reply' describes the job, " +
    "not a guaranteed result). " +
    "(3) PROOF — one real business already using her (never overclaim more than the one real paying " +
    "customer). Don't claim an industry match that isn't true: for a non-tour-operator lead, 'one tour " +
    "operator' reads as 'not my situation' — say 'She's already working alongside another small business " +
    "every day' instead. Geography-conditional too: for a CARIBBEAN lead, naming the proof customer as " +
    "Bahamian is fine and adds credibility ('another Bahamian business'). For a NON-Caribbean lead, drop " +
    "'Bahamian' from this beat as well, same reasoning as beat (2) — naming the Bahamas to a Mexican or US " +
    "lead undercuts the point of not leading with geography. Once a same-industry customer exists, switch " +
    "to naming that match ('another restaurant...') — not before it's actually true. " +
    "(4) CTA — one short, conversational close: 'Want to see it in action?' (default) or 'Worth a look?' / " +
    "'Can I show you?' as alternates to test — never the flatter 'Interested?', never a bare link bolted " +
    "onto a question as an afterthought. " +
    "CLARITY — write at an 8th-grade reading level. Every sentence should be understandable in under two " +
    "seconds. Cut any word that doesn't change the meaning; cold email rewards brutal simplicity over " +
    "elegant phrasing. " +
    "PERSONALIZATION — exactly ONE sentence (the HOOK) is personalized to this lead; beats (2)-(4) should " +
    "be the SAME wording across a whole batch, not just 'near-identical' — that sameness is intentional " +
    "now, not a bulk-generated tell, because the personalization signal lives entirely in the HOOK. Still " +
    "vary the " +
    "HOOK's opening structure/verb between leads in the same batch (don't reuse 'While you're busy running " +
    "X' verbatim for every lead) — but never pad it into a generic category truism ('Restaurant teams are " +
    "usually too busy running the floor...' could paste into any restaurant's email unchanged — confirmed " +
    "live 2026-07-29 — that is not personalization even with the business's real name elsewhere in the " +
    "email). Name the business, state the universal truth, move on. " +
    "OTHER RULES (grilled/confirmed live across 2026-07-23 and 2026-07-29 — real batches violated all of " +
    "these): " +
    "No em dashes, and no manual '--' standing in for one — comma or period only, per the voice profile " +
    "(confirmed live: a draft used '--' to bolt a self-intro onto an opening observation). " +
    "Sign-off is 'Lamar' alone on a first-touch cold email — never a second line with the company name; " +
    "the founder/company identification already happened in beat (2), don't repeat it in the signature " +
    "(confirmed live: a draft signed 'Lamar / TropiTech Solutions'). " +
    "Never invent scarcity — no fabricated beta-spot counts, deadlines, or limited-slot claims that aren't " +
    "real; the self-serve demo (meetcaye.com, 'Try for Free') is always available, describe it as such. " +
    "LENGTH — word count, not sentence count: target 50-70 words total, hard cap 90. Counting sentences " +
    "instead of words previously pushed drafts toward comma-spliced run-ons just to hit a sentence quota — " +
    "don't do that; split into a normal short sentence instead if a beat needs two clauses. " +
    "Pass the " +
    "subject as `subject` and the body as `draft`. This tool ONLY creates the lead + a held thread with " +
    "your draft sitting in the dashboard's Review tab for the operator to read, edit, and send " +
    "themselves — this tool itself does not send, regardless of how many leads are in the list " +
    "or how the operator phrases the request. Only available on the internal_sales (cold-outreach) " +
    "workspace — will error on any other workspace.",
  risk: 'low',
  roles: ['owner', 'founder'],
  modes: ['back-office'],
  inputSchema: {
    type: 'object',
    properties: {
      leads: {
        type: 'array',
        description: 'One entry per lead from the pasted list.',
        items: {
          type: 'object',
          properties: {
            email: { type: 'string', description: "The lead's email address." },
            business_name: { type: 'string', description: 'Business name, if known.' },
            contact_name: { type: 'string', description: 'Contact person\'s name, if known.' },
            subject: {
              type: 'string',
              description:
                'Short, plain subject line for this first-touch email. Required — there is no ' +
                'existing thread to inherit a subject from at this stage.',
            },
            draft: {
              type: 'string',
              description:
                "The cold-opener email body you wrote for this lead, signed as the founder, " +
                'never as Caye or an AI. Body only, no subject line, no em dashes.',
            },
          },
          required: ['email', 'subject', 'draft'],
        },
      },
    },
    required: ['leads'],
  },

  async execute(args, ctx) {
    if (!args.leads || args.leads.length === 0) {
      return { ok: false, error: 'No leads provided' }
    }

    const supabase = createServiceClient()

    const { data: workspace } = await supabase
      .from('customers')
      .select('workspace_kind')
      .eq('id', ctx.workspaceId)
      .maybeSingle()
    if (!hasSalesCapability(workspace)) {
      return {
        ok: false,
        error: 'This tool only works on the cold-outreach (internal_sales) workspace.',
      }
    }

    const { data: account } = await supabase
      .from('connected_accounts')
      .select('id')
      .eq('user_id', ctx.workspaceId)
      .eq('channel_type', 'email')
      .eq('is_active', true)
      .maybeSingle()
    if (!account) {
      return { ok: false, error: 'No active email connection on this workspace yet.' }
    }

    const created: string[] = []
    const skipped: string[] = []
    const errors: string[] = []

    for (const lead of args.leads) {
      const email = lead.email.trim().toLowerCase()
      const draft = lead.draft.trim()
      const subject = lead.subject?.trim()
      if (!email || !draft || !subject) {
        errors.push(`${lead.email || '(missing email)'}: missing email, subject, or draft`)
        continue
      }

      const { data: insertedLead, error: leadErr } = await supabase
        .from('outreach_leads')
        .insert({
          workspace_id: ctx.workspaceId,
          lead_email: email,
          business_name: lead.business_name ?? null,
          contact_name: lead.contact_name ?? null,
          status: 'draft',
        })
        .select('id')
        .single()

      if (leadErr) {
        // Unique violation (workspace_id, lead_email) — already a lead on file.
        if (leadErr.code === '23505') {
          skipped.push(email)
        } else {
          errors.push(`${email}: ${leadErr.message}`)
        }
        continue
      }

      const { error: convErr } = await supabase.from('unified_conversations').insert({
        connected_account_id: account.id,
        channel_type: 'email',
        channel_conversation_id: `outreach_${insertedLead.id}`,
        // Not ?? — Caye sometimes sends contact_name/business_name as "" rather
        // than omitting the field, and "" ?? x still returns "" (nullish
        // coalescing only falls through on null/undefined). That was leaving
        // customer_name blank — displaying as "Unknown" — for every lead
        // where no contact name was known, even though business_name was
        // correctly saved right next to it.
        customer_name: lead.contact_name?.trim() || lead.business_name?.trim() || email,
        customer_id: email,
        status: 'open',
        is_archived: false,
        human_agent_enabled: true,
        human_agent_reason: 'First-touch draft ready for review',
        metadata: {
          source: 'outreach_leads',
          lead_id: insertedLead.id,
          hold_kind: 'outreach_first_touch',
          subject,
          proposed_reply: draft,
        },
      })

      if (convErr) {
        errors.push(`${email}: thread creation failed (${convErr.message})`)
        continue
      }

      created.push(email)
    }

    return {
      ok: true,
      data: {
        created_count: created.length,
        created,
        skipped_existing: skipped,
        errors,
      },
    }
  },
}
