export type EpistemicKind = 'observed_live'|'durable_memory'|'explicit_human'|'inference'|'prediction'|'unknown'|'validated_learning'
export interface EpistemicEvidence { label:string; value:string; kind:EpistemicKind; confidence?:number|null; expiresAt?:string|null; sourceLabel?:string|null; contradictedBy?:string[]; supersedes?:string[]; environment?:'simulated'|'branch'|'test'|'production'|null }
export interface EpistemicSummary { known:string[]; inferred:string[]; predictions:string[]; unknown:string[]; stale:string[]; conflicts:string[]; rendered:string }
const LABEL:Record<EpistemicKind,string>={observed_live:'Observed live',durable_memory:'Remembered',explicit_human:'Human-provided',inference:'Inferred',prediction:'Prediction',unknown:'Unknown',validated_learning:'Validated lesson'}
function confidence(v?:number|null){return v==null?'certainty unknown':`${Math.round(Math.max(0,Math.min(1,v))*100)}% confidence`}
function stale(i:EpistemicEvidence,now:Date){if(!i.expiresAt)return false;const t=Date.parse(i.expiresAt);return Number.isFinite(t)&&t<=now.getTime()}
function safeKind(i:EpistemicEvidence):EpistemicKind{return i.kind==='observed_live'&&i.environment&&i.environment!=='production'?'inference':i.kind}
function line(i:EpistemicEvidence,k:EpistemicKind){const s=i.sourceLabel?`; source: ${i.sourceLabel}`:'';const e=i.environment?`; environment: ${i.environment}`:'';return `${LABEL[k]}: ${i.label}: ${i.value} (${confidence(i.confidence)}${s}${e})`}
export function summarizeEpistemicEvidence(items:EpistemicEvidence[],now=new Date()):EpistemicSummary{const known:string[]=[],inferred:string[]=[],predictions:string[]=[],unknown:string[]=[],old:string[]=[],conflicts:string[]=[];for(const i of items){const k=safeKind(i),l=line(i,k);if(stale(i,now))old.push(`${l}; stale since ${i.expiresAt}`);else if(k==='inference')inferred.push(l);else if(k==='prediction')predictions.push(l);else if(k==='unknown')unknown.push(l);else known.push(l);if(i.contradictedBy?.length)conflicts.push(`${i.label} has ${i.contradictedBy.length} contradictory validated source${i.contradictedBy.length===1?'':'s'}.`)}const sections:string[]=[];if(known.length)sections.push(`What I know\n${known.map(v=>`- ${v}`).join('\n')}`);if(inferred.length)sections.push(`What I infer\n${inferred.map(v=>`- ${v}`).join('\n')}`);if(predictions.length)sections.push(`Predictions\n${predictions.map(v=>`- ${v}`).join('\n')}`);if(unknown.length)sections.push(`What is unknown\n${unknown.map(v=>`- ${v}`).join('\n')}`);if(old.length)sections.push(`Stale evidence\n${old.map(v=>`- ${v}`).join('\n')}`);if(conflicts.length)sections.push(`Conflicts\n${conflicts.map(v=>`- ${v}`).join('\n')}`);return{known,inferred,predictions,unknown,stale:old,conflicts,rendered:sections.join('\n\n')}}
export function chooseAuthoritativeEvidence(items:EpistemicEvidence[]):EpistemicEvidence|null{if(!items.length)return null;const rank:Record<EpistemicKind,number>={explicit_human:6,observed_live:5,durable_memory:4,validated_learning:3,inference:2,prediction:1,unknown:0};return[...items].sort((a,b)=>rank[safeKind(b)]-rank[safeKind(a)]||(b.confidence??0)-(a.confidence??0))[0]}
