import 'server-only'
import { createServiceClient } from '@/lib/supabase-server'
import { enqueueEscalationPings, resolveEscalationRecipients } from './triggers'
import { labelForCategory } from './escalation'
import { classifyHoldUrgency } from './urgency'
import { resolveOperatorByPhone } from '@/lib/operator-identity'
import type { EscalationCategory } from '@/lib/caye-reply'

/**
 * Shared state for caye_escalations "aging" handling, split across two
 * independent call sites (see decisions-log.md 2026-07-21 — the merge was
 * triggered by Karenda getting a separate WhatsApp text per stale
 * escalation, one hourly cron tick at a time):
 *
 *   - app/api/caye/escalation-followup/cron/route.ts (hourly, all
 *     workspaces): owns resolved-detection, expiry (log-only, no ping),
 *     and the founder-threshold backstop. Never sends an owner-facing
 *     ping itself anymore.
 *   - app/api/caye/morning-digest/route.ts (once/day, 7am local per
 *     workspace): owns the owner-facing "still aging" list, folded into
 *     the morning_digest message instead of a standalone ping per
 *     escalation.
 */

export const ESCALATION_FOLLOWUP_HOURS = 6
export const FOLLOWUP_REPEAT_HOURS = 24 // re-surface once a day until resolved
export const LOOKBACK_HOURS = 24 * 30 // 30 days — a sane outer bound, not a silent-abandon trigger

export const FOUNDER_ESCALATION_HOURS = 24 * 7 // 7 days — normal categories
export const FOUNDER_ESCALATION_URGENT_HOURS = 24 // time-sensitive holds

// Bookkeeping-only close-out for escalations with no target_date, so they
// don't sit "open" forever once the founder backstop has already fired and
// nothing further is happening. Anchored off founder_escalated_at (owner-
// routed rows) or created_at + the applicable founder threshold (founder/
// both-routed rows, which never get a separate founder_escalated_at ping
// since the founder was already in the loop from creation). Does NOT touch
// the conversation's human_agent_enabled — the customer's hold is real and
// stays real; this only stops the escalation row from reading as "actively
// escalated" in get_held_queue and future cron runs (2026-07-22 pile-up fix,
// see decisions-log.md).
export const ESCALATION_BOOKKEEPING_EXPIRY_HOURS = 24 * 7 // +7 days after founder ping

// Oldest-first cap on the digest's aging list — keeps the WhatsApp template
// placeholder short and predictable regardless of backlog size.
export const AGING_LIST_MAX_ITEMS = 4

export interface EscalationRow {
  id: string
  workspace_id: string
  conversation_id: string | null
  category: string
  route_to: 'owner' | 'founder' | 'both'
  customer_facing_message: string
  internal_context: string
  ping_summary: string | null
  created_at: string
  founder_escalated_at: string | null
  target_date: string | null
}

/**
 * Plain-language "still waiting" summary, used for the founder backstop
 * ping. Reads row.ping_summary (the clean summary persisted at
 * escalation-creation time — see lib/whatsapp/escalation.ts) — never
 * internal_context, which is dashboard-only debug text that must not reach
 * an operator's WhatsApp. Legacy rows created before this column existed
 * just get the category label.
 */
export function composeFollowupPingSummary(
  row: Pick<EscalationRow, 'ping_summary' | 'category'>
): string {
  const cleanSummary = row.ping_summary ?? labelForCategory(row.category as EscalationCategory)
  return `Still waiting — ${cleanSummary}`.slice(0, 200)
}

export function formatAge(ageHours: number): string {
  return ageHours >= 24 ? `${Math.floor(ageHours / 24)}d` : `${Math.floor(ageHours)}h`
}

export async function operatorRepliedSince(conversationId: string, sinceISO: string): Promise<boolean> {
  const supabase = createServiceClient()
  const { data } = await supabase
    .from('unified_messages')
    .select('id, metadata')
    .eq('conversation_id', conversationId)
    .eq('sender_type', 'business')
    .eq('is_internal', false)
    .gt('sent_at', sinceISO)
    .limit(5)
  if (!data?.length) return false
  // Anything outbound that wasn't auto-generated by Caye counts as the
  // operator handling the thread directly.
  return data.some((m) => {
    const meta = (m.metadata ?? {}) as Record<string, unknown>
    return meta.is_automated !== true && meta.generated_by !== 'caye'
  })
}

export async function resolveContactName(conversationId: string | null): Promise<string> {
  if (!conversationId) return 'A guest'
  const supabase = createServiceClient()
  const { data: conv } = await supabase
    .from('unified_conversations')
    .select('customer_name')
    .eq('id', conversationId)
    .maybeSingle()
  return conv?.customer_name ?? 'A guest'
}

/**
 * Loop the founder in once an 'owner'-only escalation has sat unresolved
 * past a threshold. Not an autonomous action on the customer side — this
 * only adds a recipient to a founder-routed escalation_followup ping, so a
 * human (the founder) becomes the backstop when the operator won't decide.
 * Skips rows already routed to 'founder' or 'both' (founder's already in
 * the loop) and fires at most once per escalation (founder_escalated_at is
 * a one-shot marker). Unaffected by the 2026-07-21 digest-merge change —
 * this still goes out as its own immediate WhatsApp ping, to a different
 * recipient than the one the merge was fixing.
 */
export async function maybeEscalateToFounder(
  row: EscalationRow,
  contactName: string,
  pingSummary: string
): Promise<boolean> {
  if (row.founder_escalated_at) return false
  if (row.route_to === 'founder' || row.route_to === 'both') return false

  const ageHours = (Date.now() - new Date(row.created_at).getTime()) / (60 * 60 * 1000)
  const urgent =
    classifyHoldUrgency({
      inboundBody: `${row.internal_context} ${row.customer_facing_message}`,
    }) === 'urgent'
  const threshold = urgent ? FOUNDER_ESCALATION_URGENT_HOURS : FOUNDER_ESCALATION_HOURS
  if (ageHours < threshold) return false

  const ageLabel = formatAge(ageHours)

  try {
    await enqueueEscalationPings(
      {
        workspaceId: row.workspace_id,
        escalationId: row.id,
        conversationId: row.conversation_id,
        contactName,
        category: row.category,
        routeTo: 'founder',
        suggestedReply: row.customer_facing_message,
        internalContext: row.internal_context,
        pingSummary: `Operator hasn't acted in ${ageLabel} — ${pingSummary}`.slice(0, 200),
        timestamp: new Date().toISOString(),
      },
      'escalation_followup'
    )
  } catch (err) {
    console.error('[escalation-followup] founder escalation enqueue failed:', err)
    return false
  }

  const supabase = createServiceClient()
  await supabase
    .from('caye_escalations')
    .update({ founder_escalated_at: new Date().toISOString() })
    .eq('id', row.id)

  return true
}

/**
 * Should this escalation be closed out as bookkeeping-only (no target_date
 * path applies)? See ESCALATION_BOOKKEEPING_EXPIRY_HOURS docstring — this
 * governs eligibility only; expireEscalationBookkeepingOnly does the write.
 */
export function shouldExpireBookkeeping(row: EscalationRow): boolean {
  const now = Date.now()
  const bufferMs = ESCALATION_BOOKKEEPING_EXPIRY_HOURS * 60 * 60 * 1000

  if (row.founder_escalated_at) {
    return now - new Date(row.founder_escalated_at).getTime() > bufferMs
  }

  // route_to === 'owner' rows with no founder_escalated_at yet haven't hit
  // the founder backstop threshold — not eligible until they do.
  if (row.route_to !== 'founder' && row.route_to !== 'both') return false

  // founder/both-routed rows never get a founder_escalated_at ping (the
  // founder's already in the loop from creation) — anchor off created_at
  // plus the threshold that would have applied, so the total window matches
  // the owner-routed case.
  const urgent =
    classifyHoldUrgency({
      inboundBody: `${row.internal_context} ${row.customer_facing_message}`,
    }) === 'urgent'
  const thresholdMs = (urgent ? FOUNDER_ESCALATION_URGENT_HOURS : FOUNDER_ESCALATION_HOURS) * 60 * 60 * 1000
  return now - new Date(row.created_at).getTime() > thresholdMs + bufferMs
}

/**
 * Bookkeeping-only close-out: marks expired_at and logs an internal note
 * (dashboard-visible via caye_operator_messages, no WhatsApp send) so
 * there's an audit trail — but deliberately does NOT touch the
 * conversation's human_agent_enabled flag. The customer's hold is a real,
 * unresolved fact; this function only stops caye_escalations bookkeeping
 * from claiming the row is still under active automated escalation.
 *
 * Note text is per-recipient-role (2026-07-23 fix): the original version
 * used one fixed "founder already notified" string for everyone, which
 * read as confusing internal jargon when it landed in an OWNER's Caye
 * Direct thread on an owner-routed row (the owner has no reason to care
 * that the founder was pinged — what matters to them is that the thread
 * is still sitting on THEM, unresolved).
 */
export async function expireEscalationBookkeepingOnly(
  row: EscalationRow,
  contactName: string
): Promise<void> {
  const supabase = createServiceClient()

  const recipients = await resolveEscalationRecipients(row.workspace_id, row.route_to)
  for (const recipient of recipients) {
    const closingNote = (
      recipient.role === 'founder'
        ? `No further auto-follow-up on ${contactName} from me — you were already looped in, ` +
          `still unresolved. The thread itself is still held and waiting on a reply.`
        : `Letting the auto-nagging go on ${contactName} — it's been sitting a while now. ` +
          `The thread is still held and still needs your call; I just won't keep bringing it up daily.`
    ).slice(0, 200)

    const operator = await resolveOperatorByPhone(supabase, row.workspace_id, recipient.phone)
    await supabase.from('caye_operator_messages').insert({
      workspace_id: row.workspace_id,
      direction: 'outbound',
      wa_message_id: null,
      body: closingNote,
      intent: null,
      operator_allowlist_id: operator?.id ?? null,
      operator_name: operator?.name ?? null,
      operator_role: operator?.role ?? null,
    })
  }

  await supabase
    .from('caye_escalations')
    .update({ expired_at: new Date().toISOString() })
    .eq('id', row.id)
}

/**
 * One-shot closing note for an escalation whose target_date has passed
 * with no operator response. Used to read "letting this go — no reply
 * needed" as a standalone WhatsApp ping — as of 2026-07-21 it's log-only:
 * writes directly to caye_operator_messages (visible in Caye Direct's
 * dashboard history for whoever the escalation was routed to) without
 * sending anything over WhatsApp, since the message content itself said
 * there was nothing left to act on. Marks expired_at so the row drops out
 * of both this cron's and the digest's selection queries, and clears the
 * conversation's hold flag so it also drops out of the inbox's
 * needs-review view.
 */
export async function expireEscalationLogOnly(
  row: EscalationRow,
  contactName: string
): Promise<void> {
  const supabase = createServiceClient()
  const dateLabel = row.target_date
    ? new Date(`${row.target_date}T00:00:00Z`).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        timeZone: 'UTC',
      })
    : 'that window'
  const closingNote =
    `Letting this go — ${contactName}'s ${dateLabel} date already passed with no word from you.`.slice(
      0,
      200
    )

  const recipients = await resolveEscalationRecipients(row.workspace_id, row.route_to)
  for (const recipient of recipients) {
    const operator = await resolveOperatorByPhone(supabase, row.workspace_id, recipient.phone)
    await supabase.from('caye_operator_messages').insert({
      workspace_id: row.workspace_id,
      direction: 'outbound',
      wa_message_id: null,
      body: closingNote,
      intent: null,
      operator_allowlist_id: operator?.id ?? null,
      operator_name: operator?.name ?? null,
      operator_role: operator?.role ?? null,
    })
  }

  await supabase
    .from('caye_escalations')
    .update({ expired_at: new Date().toISOString() })
    .eq('id', row.id)

  if (row.conversation_id) {
    await supabase
      .from('unified_conversations')
      .update({ human_agent_enabled: false })
      .eq('id', row.conversation_id)
  }
}
